// examples/nuxt/app.vue
<template>
    <main>
        <h1 data-test-id="page-title">env-attr-cleaner — Nuxt Example</h1>

        <section data-test-id="login-section">
            <form data-test-id="login-form" @submit.prevent="handleSubmit">
                <input
                    data-test-id="login-email"
                    data-test-class="form-input"
                    type="email"
                    v-model="email"
                    placeholder="Email"
                />
                <input
                    data-test-id="login-password"
                    data-test-class="form-input"
                    type="password"
                    v-model="password"
                    placeholder="Password"
                />
                <button
                    data-test-id="login-submit"
                    data-test-class="form-button"
                    type="submit"
                >
                    Login
                </button>
            </form>
        </section>
    </main>
</template>

<script setup lang="ts">
const email = ref('')
const password = ref('')

function handleSubmit(): void {
    console.log('submitted')
}
</script>

// examples/svelte/src/App.svelte
<script lang="ts">
let email = $state('')
let password = $state('')

function handleSubmit(e: SubmitEvent): void {
    e.preventDefault()
    console.log('submitted')
}
</script>

<main>
    <h1 data-test-id="page-title">env-attr-cleaner — Svelte Example</h1>

    <section data-test-id="login-section">
        <form data-test-id="login-form" onsubmit={handleSubmit}>
            <input
                data-test-id="login-email"
                data-test-class="form-input"
                type="email"
                bind:value={email}
                placeholder="Email"
            />
            <input
                data-test-id="login-password"
                data-test-class="form-input"
                type="password"
                bind:value={password}
                placeholder="Password"
            />
            <button
                data-test-id="login-submit"
                data-test-class="form-button"
                type="submit"
            >
                Login
            </button>
        </form>
    </section>
</main>
